repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      pass_filenames: true
#      exclude: __init__.py
